version: '2'
services:
  mongodb:
    container_name: mdb
    image: mongo:3.2
    command: mongod --smallfiles
  services:
    container_name: vtube-svc
    image: darth.json/vtube-services
    depends_on: # ensures that the data-store is started first
      - mongodb
    ports:
      - "8080:8080"
    links:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb/vtube